#!/bin/sh


if [ -z $CTAGS_TYPE ]; then
	exit
fi


TOPLEVEL=`git rev-parse --show-toplevel`
cd $TOPLEVEL

if [ "$CTAGS_TYPE" = "exctags" ]; then
$CTAGS \
	--langdef=Prolog \
	--langmap=Prolog:.pl \
       	--regex-Prolog='/^([a-z0-9_:]{2,})/\1/p,predicate,predicate definition/' \
	--exclude="docs/*" \
	--extra=f \
	-R .
elif [ "$CTAGS_TYPE" = "emacs" ]; then
	ctags -l prolog `find . -name *.pl` -l prolog balance/balancer formula/compounder -l prolog `find . -name *.in`
else
	echo "What kind of CTags is that !?"
	exit 1
fi

