#!/bin/sh
#setup-np.sh: A script for me to use to configure commit tracking and pushing to two origins
#(C) Copyright 2014 Nicholas Paun

TOPLEVEL=`git rev-parse --show-toplevel`

if [ -z $2 ]; then
SHORTNAME=`echo $1 | sed s_^.*/__`
else
SHORTNAME=$2
fi

echo "#!/bin/sh" >> $TOPLEVEL/.git/hooks/post-commit

echo "Enabling commit tracking"
echo "~/repotools/repotrack &" >> $TOPLEVEL/.git/hooks/post-commit
echo "echo Reporting commit to server" >> $TOPLEVEL/.git/hooks/post-commit
echo "~/repotools/runtags &" >> $TOPLEVEL/.git/hooks/post-commit

echo "Setting up multi-remotes"

git remote set-url --add --push origin https://np@scm.icebergsys.net/git/$1
git remote set-url --add --push origin https://nicholaspaun@github.com/nicholaspaun/$SHORTNAME.git
